server:
  port: 9090

spring:
 application:
  name: qdbusers
  
 datasource:
   url: jdbc:mysql://localhost:3306/qdb
   username: root
   password: root
 
   
 jpa:
  hibernate:
     ddl-auto: update
  
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8010/eureka
      
management:
 health:
  circuitbreakers:
   enabled: true
 endpoints:
  web:
   exposure:
      include: health		    
 endpoint:
  health:
   show-details: always 
      
resilience4j:
 circuitbreaker:
    instances:
      postsAndCommentsService:
       registerHealthIndicator: true
       eventConsumerBufferSize: 10
       failureRateThreshold: 50
       minimumNumberOfCalls: 5
       automaticTransitionFromOpenToHalfOpenEnabled: true
       waitDurationInOpenState: 15s
       permittedNumberOfCallsInHalfOpenState: 3
       slidingWindowSize: 10
       slidingWindowType: COUNT_BASED 
      